on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 20.x ]

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Verify the folder structure and current directory
      - name: Debug folder structure
        run: |
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -R

      # Step 3: Set up Node.js environment, but specifically target the `Web` directory
      - name: Use Node.js ${{ matrix.node-version }} in Web directory
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Step 4: Verify Node.js is correctly set up
      - name: Verify Node.js version
        run: node -v

      # Step 5: Debug: Check the Web directory's contents
      - name: Verify Web directory contents
        run: ls -R Web

      # Step 6: Install dependencies in the Web directory
      - name: Install dependencies
        working-directory: Web
        run: |
          npm config get cache
          npm install

      # Step 7: Run tests from the Web directory
      - name: Run tests
        working-directory: Web
        run: npm run test
