on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Use stable Node.js versions
        node-version: [ 20.x ]

    steps:
      # Checkout repository
      - uses: actions/checkout@v4
      
      # Set up Node.js environment
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Debug: Check folder structure
      - name: Debug folder structure
        run: ls -R

      # Install dependencies
      - name: Install dependencies
        run: cd Web && npm ci

      # Run tests
      - name: Run tests
        run: cd Web && npm run test
