name: web && api

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - uses: actions/checkout@v4
      
      # Set up Node.js environment
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      # Install dependencies in the 'web' directory
      - name: Install dependencies
        run: |
          cd web
          npm ci

      # Run UI tests
      - name: Run Ui tests
        run: |
          cd web
          npm run test
